/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Conexion;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Armandfly
 */
public class frmCita extends javax.swing.JFrame {

    /**
     * Creates new form frmCita
     */
    public frmCita() {
        initComponents();
        txtFecha.setText(fechasistema());
    }

    public static String fechasistema() {

        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/MM/YYYY");
        return formatofecha.format(fecha);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtid_pac = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        btmBuscarPaciente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbPieza = new javax.swing.JComboBox();
        cmbCara = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cmbTratamiento = new javax.swing.JComboBox();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTrat_Citas = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtapellido = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtmotivo = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtcausa = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblfoto = new javax.swing.JLabel();
        txtnomimagen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btncargar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        cmbtipofoto = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdescripcionfoto = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        txtid_cita = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtregistrocitas = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtidcita = new javax.swing.JTextField();
        txtfechaR = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtdetallecitas = new javax.swing.JTable();
        btnMostrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblfoto2 = new javax.swing.JLabel();
        txtruta = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtFoto = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtcausaR = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtmotivoR = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("id_ pac");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cedula: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Direccion:");

        txtid_pac.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtcedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtnombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtdireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btmBuscarPaciente.setBackground(new java.awt.Color(255, 255, 255));
        btmBuscarPaciente.setText("BUSCAR PACIENTE");
        btmBuscarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmBuscarPacienteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fecha:");

        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("MOTIVO DE LA CONSULTA");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("PIEZA DENTAL:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("CAUSA-HISTORIA");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("CARA:");

        cmbPieza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO APLICA", "#55", "#54", "#53", "#52", "#51", "#85", "#84", "#83", "#82", "#81", "#61", "#62", "#63", "#64", "#65", "#71", "#72", "#73", "#74", "#75", "#18", "#17", "#16", "#15", "#14", "#13", "#12", "#11", "#21", "#22", "#23", "#24", "#25", "#26", "#27", "#28", "#48", "#47", "#46", "#45", "#44", "#43", "#42", "#41", "#31", "#32", "#33", "#34", "#35", "#36", "#37", "#38", " " }));

        cmbCara.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NO APLICA", "PIEZA COMPLETA", "CARA 1", "CARA 2", "CARA 3", "CARA 4", "CARA 5" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("TRATAMIENTO:");

        cmbTratamiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PULPOPTOMIA", "PULPECTOMIA", "EXODONCIA SIMPLE", "OPERATORIA", "ENDODONCIA", "EXODONCIA", "MEDICINA ORAL", "OPERATORIA", "PERIDONCIA", "PROTESIS", "CIRUJIA", "OTRO" }));

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("ADD");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jtTrat_Citas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PIEZA DENTAL", "CARA", "TRATAMIENTO", "OBSERVACION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtTrat_Citas);

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");

        btnGuardar.setBackground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GRABAR CITA");

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("DEL");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtmotivo.setColumns(10);
        txtmotivo.setRows(5);
        jScrollPane8.setViewportView(txtmotivo);

        txtcausa.setColumns(20);
        txtcausa.setRows(5);
        jScrollPane9.setViewportView(txtcausa);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(btmBuscarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(89, 89, 89)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtid_pac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnLimpiar)
                            .addGap(18, 18, 18)
                            .addComponent(btnGuardar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cmbPieza, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbCara, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cmbTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnAgregar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnEliminar))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtapellido))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(32, 32, 32)
                                        .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(17, 17, 17)
                                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btmBuscarPaciente)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(txtid_pac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnGuardar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CITAS", jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfoto, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfoto, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("//:");

        btncargar.setText("BUSCAR ARCHIVO");
        btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("TIPO:");

        cmbtipofoto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "RADIOLOGICA", "FOTOGRAFIA" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("DESCRIPCION:");

        txtdescripcionfoto.setColumns(20);
        txtdescripcionfoto.setRows(5);
        jScrollPane2.setViewportView(txtdescripcionfoto);

        jButton7.setText("LIMPIAR FORMULARIO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnomimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 188, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cmbtipofoto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(btncargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(txtid_cita, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtid_cita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnomimagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(cmbtipofoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15)
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton7)
                        .addGap(69, 69, 69)
                        .addComponent(btncargar)))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("GUARDAR FOTO", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtregistrocitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD.", "FECHA", "MOTIVO", "CAUSA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtregistrocitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtregistrocitasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtregistrocitasMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(jtregistrocitas);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 210));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("COD.");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 18, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("FECHA:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("MOTIVO");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));
        jPanel4.add(txtidcita, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 59, -1));
        jPanel4.add(txtfechaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 105, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("HISTORIA-ENFERMEDAD");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        jtdetallecitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TRATAMIENTO", "PIEZA DENTAL", "CARA/SECCION", "OBSERVACION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtdetallecitas);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, 110));

        btnMostrar.setText("MOSTRAR CITAS");
        jPanel4.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 160, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Fotografias de la cita");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 20));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfoto2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfoto2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 390, 270));
        jPanel4.add(txtruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 160, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("DETALLE DE LA CITA");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 20));

        jtFoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DESCRIPCION", "TIPO", "UBICACION EN EL ORDENADOR"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFotoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jtFoto);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 417, -1, 160));

        txtcausaR.setColumns(20);
        txtcausaR.setRows(5);
        jScrollPane6.setViewportView(txtcausaR);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 390, 100));

        txtmotivoR.setColumns(20);
        txtmotivoR.setRows(5);
        jScrollPane7.setViewportView(txtmotivoR);

        jPanel4.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 390, 70));

        jTabbedPane1.addTab("REGISTRO DE CITAS", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 940, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtregistrocitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtregistrocitasMouseClicked
        // TODO add your handling code here:
        int fila = jtregistrocitas.getSelectedRow();
        if (fila >= 0) {
            txtidcita.setText(jtregistrocitas.getValueAt(fila, 0).toString());
            txtfechaR.setText(jtregistrocitas.getValueAt(fila, 1).toString());
            txtmotivoR.setText(jtregistrocitas.getValueAt(fila, 2).toString());
            txtcausaR.setText(jtregistrocitas.getValueAt(fila, 3).toString());

        } else {
            JOptionPane.showMessageDialog(null, "NO HAY FILAS");
        }

        PreparedStatement psfoto = null;
        ResultSet rsfoto = null;

        PreparedStatement psdet = null;
        ResultSet rsdet = null;
        String sql = "SELECT rut_ima FROM imagencita WHERE id_cit=?";
        PreparedStatement psfotos = null;
        ResultSet rsfotos = null;
        String sqlfotos = "SELECT des_cit, tip_cit, rut_ima FROM imagencita WHERE id_cit=?";

        try {
            Conexion objCon = new Conexion();
            Connection conn = objCon.getConexion();

            //mostrar detalle citas
            DefaultTableModel modelo = new DefaultTableModel();
            jtdetallecitas.setModel(modelo);
            int codigo = Integer.parseInt(txtidcita.getText());
            psdet = conn.prepareStatement("SELECT tra_det, pie_det, car_det, obs_det FROM detallecitas WHERE id_cit=?");
            psdet.setInt(1, codigo);
            rsdet = psdet.executeQuery();

            ResultSetMetaData rsMd = rsdet.getMetaData();

            int cantidadcolumnas = rsMd.getColumnCount();

            modelo.addColumn("TRATAMIENTO.");
            modelo.addColumn("PIEZA");
            modelo.addColumn("CARA");
            modelo.addColumn("OBSERVACION");

            while (rsdet.next()) {

                Object[] filas = new Object[cantidadcolumnas];
                for (int i = 0; i < cantidadcolumnas; i++) {
                    filas[i] = rsdet.getObject(i + 1);

                }
                modelo.addRow(filas);

            }

            //MOSTRAR IMAGENES DE LA CITA
            //mostrar detalle citas
            DefaultTableModel m = new DefaultTableModel();
            jtFoto.setModel(m);

            psfotos = conn.prepareStatement(sqlfotos);
            psfotos.setInt(1, codigo);
            rsfotos = psfotos.executeQuery();

            ResultSetMetaData rsM = rsfotos.getMetaData();

            int cantidadcolumna = rsM.getColumnCount();

            m.addColumn("DESCRIPCION");
            m.addColumn("TIPO");
            m.addColumn("UBICACION");

            while (rsfotos.next()) {

                Object[] filas = new Object[cantidadcolumna];
                for (int i = 0; i < cantidadcolumna; i++) {
                    filas[i] = rsfotos.getObject(i + 1);

                }
                m.addRow(filas);

            }

            //*******************************************************
            //Cargar la foto almacenada en imagencita
           /* psfoto = conn.prepareStatement(sql);
             psfoto.setInt(1, codigo);
             rsfoto = psfoto.executeQuery();

             if (rsfoto.next()) {
             String ruta = rsfoto.getString("rut_ima");
             System.out.println(ruta);
             txtruta.setText(ruta);

             }
             Image foto = getToolkit().getImage(txtruta.getText());
             foto = foto.getScaledInstance(lblfoto2.getWidth(), lblfoto2.getHeight(), 1);
             lblfoto2.setIcon(new ImageIcon(foto));*/
        } catch (SQLException ex) {
            System.out.println(ex.toString());
        }


    }//GEN-LAST:event_jtregistrocitasMouseClicked

    private void btncargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarActionPerformed
        // TODO add your handling code here:

        if (!"".equals(txtcedula.getText())) {
            PreparedStatement psdet = null;
            ResultSet rsdet = null;
            int id_cita = 0;

            try {
                Conexion objCon = new Conexion();
                Connection conn = objCon.getConexion();
                psdet = conn.prepareStatement("SELECT * FROM citas ORDER BY id_cit DESC LIMIT 1");

                rsdet = psdet.executeQuery();

                JFileChooser fc = new JFileChooser();
                fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
                FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.PNG", "png");
                fc.setFileFilter(filtro);
                int seleccion = fc.showOpenDialog(this);

                if (seleccion == JFileChooser.APPROVE_OPTION) {

                    File fichero = fc.getSelectedFile();

                    txtnomimagen.setText(String.valueOf(fichero));
                    Image foto = getToolkit().getImage(txtnomimagen.getText());
                    foto = foto.getScaledInstance(lblfoto.getWidth(), lblfoto.getHeight(), Image.SCALE_DEFAULT);
                    lblfoto.setIcon(new ImageIcon(foto));

                    int op = JOptionPane.showConfirmDialog(null, "DESEAS GUARDAR ESTA FOTO?");
                    if (op == JOptionPane.YES_OPTION) {

                        PreparedStatement ps;
                        ResultSet rs;
                        Conexion obj = new Conexion();
                        
                        if (rsdet.next()) {
                            id_cita = Integer.parseInt(rsdet.getString("id_cit"));
                            txtid_cita.setText(rsdet.getString("id_cit"));
                            System.out.println("encontrojajajaja" + id_cita);
                            try {

                            FileInputStream fis = new FileInputStream(fichero);
                            Connection con = obj.getConexion();
                            ps = con.prepareStatement("INSERT INTO imagencita (id_cit, rut_ima, des_cit, ima_cit, tip_cit) VALUES (?,?,?,?,?)");
                            ps.setInt(1, Integer.parseInt(txtid_cita.getText()));
                            ps.setString(2, txtnomimagen.getText());
                            ps.setString(3, txtdescripcionfoto.getText());
                            ps.setBinaryStream(4, fis, (int) fichero.length());
                            ps.setString(5, String.valueOf(cmbtipofoto.getSelectedItem()));
                            ps.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Imagen Guardada");

                        } catch (HeadlessException | FileNotFoundException | SQLException ex) {
                            JOptionPane.showMessageDialog(null, "Error al Guardar Imagen");
                            System.out.println(ex);
                        }

                        } else {
                            JOptionPane.showMessageDialog(null, "GENERE LA CONSULTA PRIMERO");

                        }
                        

                    }

                }

            } catch (SQLException ex) {
                System.out.println(ex.toString());
            }

        } else {
            JOptionPane.showMessageDialog(null, "PORFAVOR PRIMERO LLENE LOS CAMPOS DE DATOS PERSONALES");
        }
    }//GEN-LAST:event_btncargarActionPerformed

    private void jtFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFotoMouseClicked
        // TODO add your handling code here:

        int fila = jtFoto.getSelectedRow();
        if (fila >= 0) {

            txtruta.setText(jtFoto.getValueAt(fila, 2).toString());

            Image foto = getToolkit().getImage(txtruta.getText());
            foto = foto.getScaledInstance(lblfoto2.getWidth(), lblfoto2.getHeight(), 1);
            lblfoto2.setIcon(new ImageIcon(foto));

        } else {
            JOptionPane.showMessageDialog(null, "NO HAY FILAS");
        }


    }//GEN-LAST:event_jtFotoMouseClicked

    private void jtregistrocitasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtregistrocitasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jtregistrocitasMouseEntered

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        txtdescripcionfoto.setText(null);
        txtnomimagen.setText(null);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int fsel = jtTrat_Citas.getSelectedRow();
        if (fsel == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione antes de borrar");
        } else {
            DefaultTableModel dtm = (DefaultTableModel) jtTrat_Citas.getModel();
            dtm.removeRow(jtTrat_Citas.getSelectedRow());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m;
        m = (DefaultTableModel) jtTrat_Citas.getModel();
        String pieza, cara, tratamiento;
        pieza = (String) cmbPieza.getSelectedItem();
        cara = (String) cmbCara.getSelectedItem();
        tratamiento = (String) cmbTratamiento.getSelectedItem();
        String elemento[] = {pieza, cara, tratamiento};
        m.addRow(elemento);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btmBuscarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBuscarPacienteActionPerformed
        // TODO add your handling code here:
        frmPacientesCita frm = new frmPacientesCita();
        frm.setVisible(true);
    }//GEN-LAST:event_btmBuscarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btmBuscarPaciente;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public static javax.swing.JButton btnMostrar;
    private javax.swing.JButton btncargar;
    public javax.swing.JComboBox cmbCara;
    public javax.swing.JComboBox cmbPieza;
    public javax.swing.JComboBox cmbTratamiento;
    private javax.swing.JComboBox cmbtipofoto;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtFoto;
    public static javax.swing.JTable jtTrat_Citas;
    public static javax.swing.JTable jtdetallecitas;
    public static javax.swing.JTable jtregistrocitas;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JLabel lblfoto2;
    public javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtapellido;
    public static javax.swing.JTextArea txtcausa;
    private javax.swing.JTextArea txtcausaR;
    public static javax.swing.JTextField txtcedula;
    private javax.swing.JTextArea txtdescripcionfoto;
    public static javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtfechaR;
    public static javax.swing.JTextField txtid_cita;
    public static javax.swing.JTextField txtid_pac;
    public static javax.swing.JTextField txtidcita;
    public static javax.swing.JTextArea txtmotivo;
    private javax.swing.JTextArea txtmotivoR;
    public static javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnomimagen;
    public static javax.swing.JTextField txtruta;
    // End of variables declaration//GEN-END:variables
}
