/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtrlAnamnesi;
import Controlador.CtrlCRUDPaciente;
import Controlador.CtrlCita;
import Controlador.CtrlOdonto;
import Controlador.CtrlOdonto16;
import Controlador.CtrlOdonto16Actual;
import Controlador.CtrlOdontoActual;
import Controlador.CtrlOdontograma;
import Controlador.CtrlOdontogramaActual;
import Controlador.CtrlOdontogramainf;
import Controlador.CtrlOdontogramainfActual;
import Controlador.CtrlOdontoinf;
import Controlador.CtrlOdontoinfactual;
import Controlador.CtrlPaciente;
import Modelo.Anamnesi;
import Modelo.Cita;
import Modelo.ConsultasAnamnesi;
import Modelo.ConsultasCita;
import Modelo.ConsultasOdonmaxinf;
import Modelo.ConsultasOdonmaxinfactual;
import Modelo.ConsultasOdontoActual;
import Modelo.ConsultasOdontograma;
import Modelo.ConsultasPaciente;
import Modelo.Odontograma;
import Modelo.Odontogramaxinf;
import Modelo.Paciente;
import javax.swing.JFrame;

/**
 *
 * @author Armandfly
 */
public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
        jLabel1.setSize(JFrame.WIDTH, JFrame.HEIGHT);
        //jMenuItem4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuConsultahistoria = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuOdontoActual = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/HD-Wallpapers1_FOSmVKg.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1660, 870));

        jMenu1.setText("HISTORIA CLINICA");

        jMenuItem1.setText("NUEVA HISTORIA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        mnuConsultahistoria.setText("CONSULTAR HISTORIAS");
        mnuConsultahistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultahistoriaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsultahistoria);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("CONSULTAS - REPORTES");

        jMenuItem3.setText("PACIENTES HISTORIA");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("CONSULTAS");

        jMenuItem5.setText("INGRESO - CONSULTA");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("ODONTOGRAMA");

        jMenuItem4.setText("ODONTOGRAMA INICIAL");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        mnuOdontoActual.setText("ODONTOGRAMA ACTUAL");
        mnuOdontoActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOdontoActualActionPerformed(evt);
            }
        });
        jMenu3.add(mnuOdontoActual);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Paciente mod = new Paciente();
        ConsultasPaciente modc = new ConsultasPaciente();
        frmPaciente frm = new frmPaciente();
        CtrlPaciente ctrl = new CtrlPaciente(mod, modc, frm);

        Anamnesi modana = new Anamnesi();
        ConsultasAnamnesi modcana = new ConsultasAnamnesi();
        CtrlAnamnesi ctrlana = new CtrlAnamnesi(modana, modcana, frm);

        ctrl.iniciar();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        frmBuscarpaciente frm = new frmBuscarpaciente();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Odontograma mod = new Odontograma();
        Odontogramaxinf modinf = new Odontogramaxinf();
        ConsultasOdontograma modc = new ConsultasOdontograma();
        ConsultasOdonmaxinf modcinf = new ConsultasOdonmaxinf();

        frmConsultasPaciente frm = new frmConsultasPaciente();
        CtrlOdontograma ctrl = new CtrlOdontograma(mod, modc, frm);
        CtrlOdontogramainf ctrlinf = new CtrlOdontogramainf(modinf, modcinf, frm);
        CtrlOdonto ctrlo = new CtrlOdonto(frm);
        CtrlOdonto16 ctrl16 = new CtrlOdonto16(frm);
        CtrlOdontoinf ctrlodinf = new CtrlOdontoinf(frm);
        frm.setTitle("ODONTOGRAMA INICIAL");
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Cita mod = new Cita();
        ConsultasCita modc = new ConsultasCita();

        frmCita frm = new frmCita();
        CtrlCita ctrl = new CtrlCita(mod, modc, frm);

        ctrl.iniciar();

        frm.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mnuConsultahistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultahistoriaActionPerformed
        // TODO add your handling code here:
        Paciente mod = new Paciente();
        ConsultasPaciente modc = new ConsultasPaciente();
        frmCDRUDPaciente frm = new frmCDRUDPaciente();
        CtrlCRUDPaciente ctrl = new CtrlCRUDPaciente(mod, modc, frm);
        ctrl.iniciar();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuConsultahistoriaActionPerformed

    private void mnuOdontoActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOdontoActualActionPerformed
        // TODO add your handling code here:

        Odontograma mod = new Odontograma();
        Odontogramaxinf modinf = new Odontogramaxinf();
        ConsultasOdontoActual modc = new ConsultasOdontoActual();
        ConsultasOdonmaxinfactual modcinf = new ConsultasOdonmaxinfactual();

        frmOdontogramaActual frm = new frmOdontogramaActual();
        CtrlOdontoActual ctrloactual = new CtrlOdontoActual(frm);
        CtrlOdonto16Actual ctrl16actual = new CtrlOdonto16Actual(frm);
        CtrlOdontogramaActual ctrl = new CtrlOdontogramaActual(mod, modc, frm);
        CtrlOdontogramainfActual ctrlinf = new CtrlOdontogramainfActual(modinf, modcinf, frm);
        CtrlOdontoinfactual ctrlodinf = new CtrlOdontoinfactual(frm);

        frm.setVisible(true);
    }//GEN-LAST:event_mnuOdontoActualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem mnuConsultahistoria;
    private javax.swing.JMenuItem mnuOdontoActual;
    // End of variables declaration//GEN-END:variables
}
